package com.dog.breed.constants

object DogBreedConstants {
    val PLATFORM: String? = "PLATFORM"
    val PHOTO: String? = "PHOTO"
    val POINTS: String? = "POINTS"
    val IMAGE_DIRECTORY_NAME: String = "Stacked"
    val PRE_SIGNED_DATA = "PRE_SIGNED_DATA"

    val STATE_BROADCAST = "com.dog.breed.STATE_BROADCAST"
    val IS_ONBOARDING_SHOWED = "IS_ONBOARDING_SHOWED"

    val BUSINESS_PROFILE = "BUSINESS_PROFILE"
    val IS_BUSINESS_USER_LOGIN = "IS_BUSINESS_USER_LOGIN"
    val IS_USER_LOGIN = "IS_USER_LOGIN"
    val ON_SIGNUP_PROCESS = "ON_SIGNUP_PROCESS"

    val IS_OTP_VERIFIED = "IS_OTP_VERIFIED"
    val IS_PROFILE_SETUP_DONE = "IS_PROFILE_SETUP_DONE"

    val LOGGED_IN_USER_DATA = "LOGGED_IN_USER_DATA"
    val LOGGED_IN_BUSINESS_USER_DATA = "LOGGED_IN_BUSINESS_USER_DATA"
    val BUSINESS_STORE_DATA = "BUSINESS_STORE_DATA"
    val CONFIG_DATA = "CONFIG_DATA"

    val AUTH_TOKEN = "AUTH_TOKEN"
    val REFRESH_TOKEN = "REFRESH_TOKEN"

    val BUSINESS_AUTH_TOKEN = "BUSINESS_AUTH_TOKEN"
    val BUSINESS_REFRESH_TOKEN = "BUSINESS_REFRESH_TOKEN"


    val OFFER_REDEEMED = "OFFER_REDEEMED"
    val OFFER_ITEM = "OFFER_ITEM"
    val STORE_ITEM = "STORE_ITEM"
    val MESSAGE_ITEM = "MESSAGE_ITEM"

    val TITLE = "TITLE"
    val PROFILE = "PROFILE"
    val URL = "URL"

    val FIREBASE_REGISTRATION_TOKEN = "FIREBASE_REGISTRATION_TOKEN"
    val IS_PUSH_TOKEN_UPDATED_ON_SERVER = "IS_PUSH_TOKEN_UPDATED_ON_SERVER"

}